// <auto-generated />
using System;
using Booking_API.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Booking_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260209134135_SeedCompany")]
    partial class SeedCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booking_API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 9, 12, 0, 0, 0, DateTimeKind.Utc),
                            Details = "Software development company",
                            Name = "Alpha Tech",
                            Rate = 4.5,
                            UpdatedDate = new DateTime(2026, 2, 9, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 9, 12, 5, 0, 0, DateTimeKind.Utc),
                            Details = "IT consulting services",
                            Name = "Beta Solutions",
                            Rate = 4.2000000000000002,
                            UpdatedDate = new DateTime(2026, 2, 9, 12, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 9, 12, 10, 0, 0, DateTimeKind.Utc),
                            Details = "Business analytics and BI",
                            Name = "Gamma Group",
                            Rate = 4.7999999999999998,
                            UpdatedDate = new DateTime(2026, 2, 9, 12, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 2, 9, 12, 15, 0, 0, DateTimeKind.Utc),
                            Details = "Cloud infrastructure services",
                            Name = "Delta Systems",
                            Rate = 4.0,
                            UpdatedDate = new DateTime(2026, 2, 9, 12, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 2, 9, 12, 20, 0, 0, DateTimeKind.Utc),
                            Details = "AI & machine learning startup",
                            Name = "Epsilon Labs",
                            Rate = 4.9000000000000004,
                            UpdatedDate = new DateTime(2026, 2, 9, 12, 20, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
